from setuptools import setup, find_packages

setup(
    name="chaosmining",
    version="0.1.0",
    description="A package to Evaluate Post-Hoc Local Attribution Methods in Low SNR Environments",
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author="Ge Shi",
    author_email="geshi@ucdavis.edu",
    url="https://github.com/geshijoker/ChaosMining",
    packages=find_packages(),
    python_requires='>=3.10',
    install_requires=[
        'numpy>=1.21.0',
        'scipy>=1.7.0',
        'pandas>=1.3.0',
        'torch>=1.10.0',  
        'torchvision>=0.11.0',  
        'matplotlib>=3.4.0',
        'seaborn>=0.11.0',
        'scikit-learn>=0.24.0',
        'notebook>=6.4.0',
        'jupyterlab>=3.0.0',
        'ipython>=7.23.0',
        'tqdm>=4.61.0',
        'requests>=2.25.0',
        'h5py>=3.3.0',
        'Pillow>=8.2.0',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.10',
    ],
)